# Generated by Django 5.0.2 on 2024-04-16 15:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LegalCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=30, verbose_name='Номер дела')),
                ('city', models.CharField(max_length=30, verbose_name='Город')),
                ('amount_debt', models.FloatField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Сумма долга')),
                ('writenoff_debt', models.FloatField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Списано долга')),
                ('number_credits', models.PositiveSmallIntegerField(verbose_name='Кредитов')),
                ('date_start_work', models.DateField(verbose_name='Начало работы')),
                ('date_case_filed', models.DateField(verbose_name='Подано')),
                ('date_declared_bankrupt', models.DateField(verbose_name='Признана банкротом')),
                ('date_case_completed', models.DateField(verbose_name='Завершено')),
                ('case_pdf', models.FileField(upload_to='', verbose_name='PDF файл дела')),
            ],
        ),
    ]
