# Generated by Django 5.0.2 on 2024-04-16 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legal_cases', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legalcase',
            name='case_pdf',
            field=models.FileField(upload_to='cases_pdf', verbose_name='PDF файл дела'),
        ),
    ]
