# Generated by Django 5.0.2 on 2024-04-17 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('legal_cases', '0002_alter_legalcase_case_pdf'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='legalcase',
            options={'verbose_name': 'Дело', 'verbose_name_plural': 'Дела'},
        ),
    ]
